Repository RhythmPalette/RhythmPalette-Server, pull requests merged in 2024-02, with the labels that each got.

#20 feat: post 생성 기능 구현
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/domain/post/dto/PostRequestDTO.java
  src/main/java/com/umc/Palette/domain/post/dto/PostResponseDTO.java
  src/main/java/com/umc/Palette/domain/post/service/PostService.java
Labels: ✨ Feature

#22 feat: 댓글 작성 구현
  src/main/java/com/umc/Palette/domain/base_time/BaseTimeEntity.java
  src/main/java/com/umc/Palette/domain/comment/controller/ApiResponse.java
  src/main/java/com/umc/Palette/domain/comment/controller/CommentRestController.java
  src/main/java/com/umc/Palette/domain/comment/converter/CommentConverter.java
  src/main/java/com/umc/Palette/domain/comment/domain/Comment.java
  src/main/java/com/umc/Palette/domain/comment/dto/CommentDto.java
  src/main/java/com/umc/Palette/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/umc/Palette/domain/comment/repository/CommentRepository.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentLikeService.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentService.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/domain/user/repository/UserRepository.java
Labels: ✨ Feature

#21 feat: 회원가입 + 로그인 구현
  build.gradle
  src/main/java/com/umc/Palette/PaletteApplication.java
  src/main/java/com/umc/Palette/config/JwtAuthenticationFilter.java
  src/main/java/com/umc/Palette/config/SecurityConfiguration.java
  src/main/java/com/umc/Palette/domain/follow/domain/Follow.java
  src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
  src/main/java/com/umc/Palette/domain/mail/domain/EmailConfig.java
  src/main/java/com/umc/Palette/domain/mail/dto/EmailAuthRequest.java
  src/main/java/com/umc/Palette/domain/mail/dto/EmailCheckRequest.java
  src/main/java/com/umc/Palette/domain/mail/service/EmailService.java
  src/main/java/com/umc/Palette/domain/mail/service/EmailServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/Role.java
  src/main/java/com/umc/Palette/domain/user/controller/AdminController.java
  src/main/java/com/umc/Palette/domain/user/controller/AuthenticationController.java
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/domain/User.java
  src/main/java/com/umc/Palette/domain/user/dto/JwtAuthenticationResponse.java
  src/main/java/com/umc/Palette/domain/user/dto/PasswordCheckRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/RefreshTokenRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/SignUpRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/SigninRequest.java
  src/main/java/com/umc/Palette/domain/user/repository/UserRepository.java
  src/main/java/com/umc/Palette/domain/user/service/AuthenticationService.java
  src/main/java/com/umc/Palette/domain/user/service/JwtService.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/JwtServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseException.java
  src/main/java/com/umc/Palette/global/exception/BaseResponse.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseService.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature, 📬 API

#28 refactor: 회원가입 + 로그인 에러 처리 리팩터링
  src/main/java/com/umc/Palette/PaletteApplication.java
  src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
  src/main/java/com/umc/Palette/domain/mail/service/EmailServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/controller/AuthenticationController.java
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: 🔨 Refactor

#32 feat/ 댓글 조회, 작성, 수정 삭제기능 추가
  src/main/java/com/umc/Palette/domain/comment/controller/ApiResponse.java
  src/main/java/com/umc/Palette/domain/comment/controller/CommentLikeRestController.java
  src/main/java/com/umc/Palette/domain/comment/controller/CommentRestController.java
  src/main/java/com/umc/Palette/domain/comment/converter/CommentConverter.java
  src/main/java/com/umc/Palette/domain/comment/converter/UserCommentLikeConverter.java
  src/main/java/com/umc/Palette/domain/comment/domain/Comment.java
  src/main/java/com/umc/Palette/domain/comment/domain/UserCommentLike.java
  src/main/java/com/umc/Palette/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/umc/Palette/domain/comment/dto/UserCommentLikeDto.java
  src/main/java/com/umc/Palette/domain/comment/repository/CommentRepository.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentLikeService.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentService.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeService.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeServiceImpl.java
  src/main/java/com/umc/Palette/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
Labels: ✨ Feature

#23 feat: post 업데이트 기능 구현
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/domain/post/dto/PostRequest.java
  src/main/java/com/umc/Palette/domain/post/dto/PostResponse.java
  src/main/java/com/umc/Palette/domain/post/repository/PostRepository.java
  src/main/java/com/umc/Palette/domain/post/service/PostService.java
Labels: ✨ Feature

#24 feat: post 삭제 기능 구현
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/post/repository/PostRepository.java
  src/main/java/com/umc/Palette/domain/post/service/PostService.java
Labels: ✨ Feature

#39 feat: post 조회 기능 구현
  build.gradle
  src/main/java/com/umc/Palette/PaletteApplication.java
  src/main/java/com/umc/Palette/config/JwtAuthenticationFilter.java
  src/main/java/com/umc/Palette/config/SecurityConfiguration.java
  src/main/java/com/umc/Palette/domain/base_time/BaseTimeEntity.java
  src/main/java/com/umc/Palette/domain/comment/controller/CommentLikeRestController.java
  src/main/java/com/umc/Palette/domain/comment/controller/CommentRestController.java
  src/main/java/com/umc/Palette/domain/comment/converter/CommentConverter.java
  src/main/java/com/umc/Palette/domain/comment/converter/UserCommentLikeConverter.java
  src/main/java/com/umc/Palette/domain/comment/domain/Comment.java
  src/main/java/com/umc/Palette/domain/comment/domain/UserCommentLike.java
  src/main/java/com/umc/Palette/domain/comment/dto/CommentDto.java
  src/main/java/com/umc/Palette/domain/comment/dto/CommentRequestDTO.java
  src/main/java/com/umc/Palette/domain/comment/dto/UserCommentLikeDto.java
  src/main/java/com/umc/Palette/domain/comment/repository/CommentRepository.java
  src/main/java/com/umc/Palette/domain/comment/service/CommentService.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeService.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeServiceImpl.java
  src/main/java/com/umc/Palette/domain/comment/service/impl/CommentServiceImpl.java
  src/main/java/com/umc/Palette/domain/follow/domain/Follow.java
  src/main/java/com/umc/Palette/domain/mail/controller/MailController.java
  src/main/java/com/umc/Palette/domain/mail/domain/EmailConfig.java
  src/main/java/com/umc/Palette/domain/mail/dto/EmailAuthRequest.java
  src/main/java/com/umc/Palette/domain/mail/dto/EmailCheckRequest.java
  src/main/java/com/umc/Palette/domain/mail/service/EmailService.java
  src/main/java/com/umc/Palette/domain/mail/service/EmailServiceImpl.java
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/domain/post/dto/PostRequestDTO.java
  src/main/java/com/umc/Palette/domain/post/dto/PostResponse.java
  src/main/java/com/umc/Palette/domain/post/dto/PostResponseDTO.java
  src/main/java/com/umc/Palette/domain/post/repository/PostLikeRepository.java
  src/main/java/com/umc/Palette/domain/post/repository/PostRepository.java
  src/main/java/com/umc/Palette/domain/post/service/PostService.java
  src/main/java/com/umc/Palette/domain/user/Role.java
  src/main/java/com/umc/Palette/domain/user/controller/AdminController.java
  src/main/java/com/umc/Palette/domain/user/controller/AuthenticationController.java
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/domain/User.java
  src/main/java/com/umc/Palette/domain/user/dto/JwtAuthenticationResponse.java
  src/main/java/com/umc/Palette/domain/user/dto/PasswordCheckRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/RefreshTokenRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/SignUpRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/SigninRequest.java
  src/main/java/com/umc/Palette/domain/user/repository/UserRepository.java
  src/main/java/com/umc/Palette/domain/user/service/AuthenticationService.java
  src/main/java/com/umc/Palette/domain/user/service/JwtService.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/JwtServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseException.java
  src/main/java/com/umc/Palette/global/exception/BaseResponse.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseService.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
  src/main/java/com/umc/Palette/global/exception/CustomExceptionHandler.java
Labels: ✨ Feature

#33 feat: 플레이리스트 관련 api 구현
  build.gradle
  src/main/java/com/umc/Palette/domain/music/controller/PlaylistController.java
  src/main/java/com/umc/Palette/domain/music/domain/Playlist.java
  src/main/java/com/umc/Palette/domain/music/dto/request/PlaylistCreateRequest.java
  src/main/java/com/umc/Palette/domain/music/dto/response/PlaylistCreateResponse.java
  src/main/java/com/umc/Palette/domain/music/dto/response/PlaylistPostResponse.java
  src/main/java/com/umc/Palette/domain/music/dto/response/PlaylistResponse.java
  src/main/java/com/umc/Palette/domain/music/dto/response/PostAddResponse.java
  src/main/java/com/umc/Palette/domain/music/service/PlaylistService.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/global/config/WebMvcConfig.java
  src/main/java/com/umc/Palette/global/config/annotation/LoggedInUser.java
  src/main/java/com/umc/Palette/global/config/handler/UserInfoArgumentResolver.java
  src/main/java/com/umc/Palette/global/exception/BaseException.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
  src/main/java/com/umc/Palette/global/exception/CustomExceptionHandler.java
Labels: ✨ Feature

#35 feat: 팔로우 요청 api 구현
  src/main/java/com/umc/Palette/domain/follow/controller/FollowController.java
  src/main/java/com/umc/Palette/domain/follow/domain/Follow.java
  src/main/java/com/umc/Palette/domain/follow/repository/FollowRepository.java
  src/main/java/com/umc/Palette/domain/follow/service/FollowService.java
  src/main/java/com/umc/Palette/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature

#37 선호 장르 api 구현
  src/main/java/com/umc/Palette/PaletteApplication.java
  src/main/java/com/umc/Palette/domain/music/domain/Music.java
  src/main/java/com/umc/Palette/domain/preference_genre/domain/PreferenceGenre.java
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/domain/User.java
  src/main/java/com/umc/Palette/domain/user/dto/ProfileRequest.java
  src/main/java/com/umc/Palette/domain/user/dto/SignUpRequest.java
  src/main/java/com/umc/Palette/domain/user/repository/UserRepository.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature

#46 Refactor/post crud
  build.gradle
  src/main/java/com/umc/Palette/config/SecurityConfiguration.java
  src/main/java/com/umc/Palette/domain/comment/repository/CommentRepository.java
  src/main/java/com/umc/Palette/domain/emotion/domain/Emotion.java
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/post/domain/Image.java
  src/main/java/com/umc/Palette/domain/post/domain/Post.java
  src/main/java/com/umc/Palette/domain/post/domain/PostLike.java
  src/main/java/com/umc/Palette/domain/post/dto/PostRequest.java
  src/main/java/com/umc/Palette/domain/post/dto/PostResponse.java
  src/main/java/com/umc/Palette/domain/post/dto/SliceResponse.java
  src/main/java/com/umc/Palette/domain/post/repository/ImageRepository.java
  src/main/java/com/umc/Palette/domain/post/repository/PostLikeRepository.java
  src/main/java/com/umc/Palette/domain/post/repository/PostRepository.java
  src/main/java/com/umc/Palette/domain/post/service/ImageService.java
  src/main/java/com/umc/Palette/domain/post/service/PostLikeService.java
  src/main/java/com/umc/Palette/domain/post/service/PostService.java
  src/main/java/com/umc/Palette/domain/situation/domain/Situation.java
  src/main/java/com/umc/Palette/domain/situation/repository/SituationRepository.java
  src/main/java/com/umc/Palette/domain/user/domain/User.java
  src/main/java/com/umc/Palette/global/config/S3Config.java
  src/main/java/com/umc/Palette/global/config/SwaggerConfig.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
  src/main/resources/data.sql
Labels: ✨ Feature, 🔨 Refactor

#44 feat: 댓글 좋아요 조회, 추가, 삭제 기능 작성
  src/main/java/com/umc/Palette/domain/comment/controller/CommentLikeRestController.java
  src/main/java/com/umc/Palette/domain/comment/converter/UserCommentLikeConverter.java
  src/main/java/com/umc/Palette/domain/comment/dto/UserCommentLikeDto.java
  src/main/java/com/umc/Palette/domain/comment/repository/UserCommentLikeRepository.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeService.java
  src/main/java/com/umc/Palette/domain/comment/service/UserCommentLikeServiceImpl.java
  src/main/java/com/umc/Palette/domain/comment/service/impl/UserCommentLikeServiceImpl.java
Labels: ✨ Feature, 📬 API

#42 feat: Music 요청 dto, 조회 메서드 구현
  src/main/java/com/umc/Palette/domain/music/controller/PlaylistController.java
  src/main/java/com/umc/Palette/domain/music/domain/Music.java
  src/main/java/com/umc/Palette/domain/music/domain/MusicGenre.java
  src/main/java/com/umc/Palette/domain/music/dto/request/MusicRequest.java
  src/main/java/com/umc/Palette/domain/music/repository/GenreRepository.java
  src/main/java/com/umc/Palette/domain/music/repository/MusicGenreRepository.java
  src/main/java/com/umc/Palette/domain/music/repository/MusicRepository.java
  src/main/java/com/umc/Palette/domain/music/service/MusicService.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature

#45 카카오 회원가입 + 로그인 구현
  build.gradle
  src/main/java/com/umc/Palette/PaletteApplication.java
  src/main/java/com/umc/Palette/domain/kakao/RandomPasswordGenerator.java
  src/main/java/com/umc/Palette/domain/kakao/controller/KakaoController.java
  src/main/java/com/umc/Palette/domain/kakao/domain/KakaoApi.java
  src/main/java/com/umc/Palette/domain/user/controller/AuthenticationController.java
  src/main/java/com/umc/Palette/domain/user/dto/KakaoSigninRequest.java
  src/main/java/com/umc/Palette/domain/user/repository/UserRepository.java
  src/main/java/com/umc/Palette/domain/user/service/AuthenticationService.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
  src/main/resources/static/login.png
  src/main/resources/templates/kakaologin.html
Labels: ✨ Feature

#49 프로필 등록시 S3 업로드 추가 구현
  build.gradle
  src/main/java/com/umc/Palette/domain/post/controller/PostController.java
  src/main/java/com/umc/Palette/domain/user/controller/AuthenticationController.java
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/dto/ProfileRequest.java
  src/main/java/com/umc/Palette/domain/user/service/FileUploadService.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature

#50 S3 버전 수정
  build.gradle
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
Labels: 🐞 BugFix

#51 fix: s3의존성 버그 수정
  build.gradle
Labels: 🐞 BugFix

#52 feat: ci/cd 적용 기능 추가
  .github/workflows/main.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/umc/Palette/domain/comment/controller/CommentLikeRestController.java
  src/main/java/com/umc/Palette/domain/comment/domain/Comment.java
Labels: ✨ Feature

#55 대표음악 설정 + 프로필 반환
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/domain/User.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
Labels: ✨ Feature

#57 상대방 프로필 방문 구현
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
  src/main/java/com/umc/Palette/domain/user/service/UserService.java
  src/main/java/com/umc/Palette/domain/user/service/impl/UserServiceImpl.java
Labels: ✨ Feature

#58 팔로우, 팔로워 끊기 구현
  src/main/java/com/umc/Palette/domain/follow/controller/FollowController.java
  src/main/java/com/umc/Palette/domain/follow/repository/FollowRepository.java
  src/main/java/com/umc/Palette/domain/follow/service/FollowService.java
  src/main/java/com/umc/Palette/domain/follow/service/FollowServiceImpl.java
  src/main/java/com/umc/Palette/global/exception/BaseResponseStatus.java
Labels: ✨ Feature

#62 PR을 통해 배포를 위한 커밋
  src/main/java/com/umc/Palette/domain/user/controller/UserController.java
Labels: 📃 Docs
